# Generated by Django 5.1.2 on 2024-11-14 15:52

import core.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Titre de la formation')),
                ('description', models.CharField(max_length=50, verbose_name='Mini description de la formation')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix')),
                ('promo_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix promotionnel')),
                ('promo_duration', models.DateTimeField(blank=True, null=True, verbose_name='Durée de la promotion')),
                ('image', models.ImageField(blank=True, upload_to='images/', verbose_name='Image de présentation')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True, verbose_name="URL de l'image de présentation")),
                ('content', models.TextField(verbose_name='Contenu de la formation')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('montant', models.FloatField()),
                ('devise_client', models.CharField(max_length=10)),
                ('status', models.CharField(default='initialiser', max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('orderId', models.CharField(max_length=10)),
                ('operator', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.formation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserFormationPurchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('achat_date', models.DateTimeField(auto_now_add=True)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_by_users', to='core.formation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_formations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Formation Acheter',
                'verbose_name_plural': 'Formation Acheter',
            },
        ),
        migrations.CreateModel(
            name='VideoFormation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Titre de la vidéo')),
                ('ordre', models.IntegerField(default=1, verbose_name="Ordre d'affichage de la formation")),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos/', validators=[core.models.validate_video_file], verbose_name='Fichier vidéo')),
                ('video_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL du fichier vidéo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='core.formation')),
            ],
        ),
    ]
