# Generated by Django 5.1.2 on 2024-11-06 08:45

import django.db.models.deletion
import django_quill.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre de la formation')),
                ('description', models.CharField(max_length=50, verbose_name='Mini description de la formation')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix')),
                ('promo_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix promotionnel')),
                ('promo_duration', models.DateTimeField(blank=True, null=True, verbose_name='Durée de la promotion')),
                ('image_url', models.URLField(blank=True, max_length=500, verbose_name="URL de l'image de présentation")),
                ('content', django_quill.fields.QuillField(verbose_name='Contenu de la formation')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
            ],
        ),
        migrations.CreateModel(
            name='VideoFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre de la vidéo')),
                ('video_url', models.URLField(blank=True, max_length=500, verbose_name='URL du fichier vidéo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='core.formation')),
            ],
        ),
    ]
