# Generated by Django 5.1.2 on 2024-11-06 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='image',
            field=models.FileField(blank=True, upload_to='images/', verbose_name='Image de présentation'),
        ),
        migrations.AddField(
            model_name='videoformation',
            name='video_file',
            field=models.FileField(blank=True, upload_to='videos/', verbose_name='Fichier vidéo'),
        ),
    ]
