# Generated by Django 5.1.2 on 2024-11-06 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_formation_image_videoformation_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='Image de présentation'),
        ),
    ]
