# Generated by Django 5.1.2 on 2024-11-06 13:19

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_formation_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='content',
            field=models.TextField(verbose_name='Contenu de la formation'),
        ),
        migrations.AlterField(
            model_name='videoformation',
            name='video_file',
            field=models.FileField(blank=True, upload_to='videos/', validators=[core.models.validate_video_file], verbose_name='Fichier vidéo'),
        ),
    ]
