# Generated by Django 5.1.2 on 2024-11-06 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_formation_content_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFormationPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achat_date', models.DateTimeField(auto_now_add=True)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_by_users', to='core.formation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_formations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Achat de formation par utilisateur',
                'verbose_name_plural': 'Achats de formations par utilisateurs',
            },
        ),
    ]
