# Generated by Django 5.1.2 on 2024-11-06 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_userformationpurchase'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userformationpurchase',
            options={'verbose_name': 'Formation Acheter', 'verbose_name_plural': 'Formation Acheter'},
        ),
    ]
