# Generated by Django 5.1.2 on 2024-11-09 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_userformationpurchase_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoformation',
            name='ordre',
            field=models.IntegerField(default=1, verbose_name="Ordre d'affichage de la formation"),
        ),
    ]
