# Generated by Django 5.1.2 on 2024-11-09 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_videoformation_ordre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name="URL de l'image de présentation"),
        ),
        migrations.AlterField(
            model_name='videoformation',
            name='video_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL du fichier vidéo'),
        ),
    ]
