# Generated by Django 5.1.2 on 2024-11-14 15:37

import core.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userformationpurchase',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='videoformation',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='videoformation',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/', validators=[core.models.validate_video_file], verbose_name='Fichier vidéo'),
        ),
    ]
