"""
Django settings for karineacademy_back project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-axyblbh1clq8zq$@uji#ks*#1ait2)hk)ko#qp8-welr2__2al'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ["*"]
CORS_ALLOW_ALL_ORIGINS = True

CORS_ALLOWED_ORIGINS = [
    "http://*","https://*"  # Remplacez ceci par l'origine de votre front-end si nécessaire
]
# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_quill',
    'core',
    'corsheaders',
]




MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'karineacademy_back.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'karineacademy_back.wsgi.application'


JAZZMIN_SETTINGS = {
    # title of the window (Will default to current_admin_site.site_title if absent or None)
    "site_title": "Karine Academy Admin",
    "site_header": "Karine Academy",
    "site_brand": "Karine Academy",
    "login_logo": False,
    "site_icon": None,
    "welcome_sign": "Bienvenue sur Karine Academy",
    "copyright": " Karine Academy",
}


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/


# Indique les répertoires dans lesquels Django recherchera les fichiers statiques
# Dans ce cas, nous ajoutons le répertoire 'static' à la racine du projet
STATICFILES_DIRS = [BASE_DIR / 'static']

# Paramètres de connexion à votre instance MinIO
MINIO_ENDPOINT = "karine-academy-bucket-karine.hegely.easypanel.host"
MINIO_ACCESS_KEY = "O8xlRP5wdXGKp3GmtL0j"
MINIO_SECRET_KEY = "ynz3HrJKTWwrBpfog5wwoVi31sZsHinNPVc86tGQ"
MINIO_IMAGE_BUCKET_NAME = "media"
MINIO_VIDEO_BUCKET_NAME = "media"
MINIO_BUCKET_STATIC = "static"
MINIO_USE_SSL = True  # Utilisez True pour les connexions sécurisées

# URL de base pour accéder aux fichiers statiques (CSS, JavaScript, images)
STATIC_URL = f"http://{MINIO_ENDPOINT}/{MINIO_BUCKET_STATIC}/"
MEDIA_URL = '/media/'
# Dossier temporaire pour collecter les fichiers statiques avant de les envoyer à MinIO
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'